import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { SidebarProvider } from "@/contexts/SidebarContext";
import SidebarComponent from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="main-content">
        <SidebarProvider>
          <SidebarComponent />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
